//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSDemo.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.GetCurrentlyBestPlayerSoap")]
    public interface GetCurrentlyBestPlayerSoap {
        
        // CODEGEN: Generating message contract since element name HockeyResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Hockey", ReplyAction="*")]
        WSDemo.ServiceReference1.HockeyResponse Hockey(WSDemo.ServiceReference1.HockeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Hockey", ReplyAction="*")]
        System.Threading.Tasks.Task<WSDemo.ServiceReference1.HockeyResponse> HockeyAsync(WSDemo.ServiceReference1.HockeyRequest request);
        
        // CODEGEN: Generating message contract since element name SoccerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Soccer", ReplyAction="*")]
        WSDemo.ServiceReference1.SoccerResponse Soccer(WSDemo.ServiceReference1.SoccerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Soccer", ReplyAction="*")]
        System.Threading.Tasks.Task<WSDemo.ServiceReference1.SoccerResponse> SoccerAsync(WSDemo.ServiceReference1.SoccerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HockeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Hockey", Namespace="http://tempuri.org/", Order=0)]
        public WSDemo.ServiceReference1.HockeyRequestBody Body;
        
        public HockeyRequest() {
        }
        
        public HockeyRequest(WSDemo.ServiceReference1.HockeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HockeyRequestBody {
        
        public HockeyRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HockeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HockeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSDemo.ServiceReference1.HockeyResponseBody Body;
        
        public HockeyResponse() {
        }
        
        public HockeyResponse(WSDemo.ServiceReference1.HockeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HockeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HockeyResult;
        
        public HockeyResponseBody() {
        }
        
        public HockeyResponseBody(string HockeyResult) {
            this.HockeyResult = HockeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoccerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Soccer", Namespace="http://tempuri.org/", Order=0)]
        public WSDemo.ServiceReference1.SoccerRequestBody Body;
        
        public SoccerRequest() {
        }
        
        public SoccerRequest(WSDemo.ServiceReference1.SoccerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SoccerRequestBody {
        
        public SoccerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoccerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoccerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSDemo.ServiceReference1.SoccerResponseBody Body;
        
        public SoccerResponse() {
        }
        
        public SoccerResponse(WSDemo.ServiceReference1.SoccerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoccerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SoccerResult;
        
        public SoccerResponseBody() {
        }
        
        public SoccerResponseBody(string SoccerResult) {
            this.SoccerResult = SoccerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetCurrentlyBestPlayerSoapChannel : WSDemo.ServiceReference1.GetCurrentlyBestPlayerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCurrentlyBestPlayerSoapClient : System.ServiceModel.ClientBase<WSDemo.ServiceReference1.GetCurrentlyBestPlayerSoap>, WSDemo.ServiceReference1.GetCurrentlyBestPlayerSoap {
        
        public GetCurrentlyBestPlayerSoapClient() {
        }
        
        public GetCurrentlyBestPlayerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetCurrentlyBestPlayerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetCurrentlyBestPlayerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetCurrentlyBestPlayerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSDemo.ServiceReference1.HockeyResponse WSDemo.ServiceReference1.GetCurrentlyBestPlayerSoap.Hockey(WSDemo.ServiceReference1.HockeyRequest request) {
            return base.Channel.Hockey(request);
        }
        
        public string Hockey() {
            WSDemo.ServiceReference1.HockeyRequest inValue = new WSDemo.ServiceReference1.HockeyRequest();
            inValue.Body = new WSDemo.ServiceReference1.HockeyRequestBody();
            WSDemo.ServiceReference1.HockeyResponse retVal = ((WSDemo.ServiceReference1.GetCurrentlyBestPlayerSoap)(this)).Hockey(inValue);
            return retVal.Body.HockeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSDemo.ServiceReference1.HockeyResponse> WSDemo.ServiceReference1.GetCurrentlyBestPlayerSoap.HockeyAsync(WSDemo.ServiceReference1.HockeyRequest request) {
            return base.Channel.HockeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSDemo.ServiceReference1.HockeyResponse> HockeyAsync() {
            WSDemo.ServiceReference1.HockeyRequest inValue = new WSDemo.ServiceReference1.HockeyRequest();
            inValue.Body = new WSDemo.ServiceReference1.HockeyRequestBody();
            return ((WSDemo.ServiceReference1.GetCurrentlyBestPlayerSoap)(this)).HockeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSDemo.ServiceReference1.SoccerResponse WSDemo.ServiceReference1.GetCurrentlyBestPlayerSoap.Soccer(WSDemo.ServiceReference1.SoccerRequest request) {
            return base.Channel.Soccer(request);
        }
        
        public string Soccer() {
            WSDemo.ServiceReference1.SoccerRequest inValue = new WSDemo.ServiceReference1.SoccerRequest();
            inValue.Body = new WSDemo.ServiceReference1.SoccerRequestBody();
            WSDemo.ServiceReference1.SoccerResponse retVal = ((WSDemo.ServiceReference1.GetCurrentlyBestPlayerSoap)(this)).Soccer(inValue);
            return retVal.Body.SoccerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSDemo.ServiceReference1.SoccerResponse> WSDemo.ServiceReference1.GetCurrentlyBestPlayerSoap.SoccerAsync(WSDemo.ServiceReference1.SoccerRequest request) {
            return base.Channel.SoccerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSDemo.ServiceReference1.SoccerResponse> SoccerAsync() {
            WSDemo.ServiceReference1.SoccerRequest inValue = new WSDemo.ServiceReference1.SoccerRequest();
            inValue.Body = new WSDemo.ServiceReference1.SoccerRequestBody();
            return ((WSDemo.ServiceReference1.GetCurrentlyBestPlayerSoap)(this)).SoccerAsync(inValue);
        }
    }
}
